name: Generate Markdown Docs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jsdoc-to-markdown
        run: npm install -g jsdoc-to-markdown

      - name: Create Markdown File
        run: jsdoc2md *.js > API.md 

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add API.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto generate documentation" && git push)

